### ISSUE TITLE
improvement : add ease fields

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ijgnd/anki21__reviewer_additional_card_fields#1]
Hi,

I think it would be useful to me to have a card's ease factor displayed on top while reviewing. Currently I am using another addon to display all info about a card and it's not very efficient. Could it be added ?

Thanks for you time spent reading this :) great addon thanks !

**Comment by ijgnd** [comment]
anki's scheduler refers to the card's ease as "factor" which you could already display with `{{info::Factor}}` (this is ease*10)

I just published a new version with `{{info::Ease}}` which should be more convenient. new cards and cards in learning have no ease/0.

Could you test and let me know if it works.

**Comment by thiswillbeyourgithub** [comment]
Indeed it works! Thank your for this :) and thanks for Factor, I didn't know!

Have a nice day!
