### ISSUE TITLE
doesn't work with conditionnal fields

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ijgnd/anki21__reviewer_additional_card_fields#5]
Hi,
I don't think this addon works with conditionnal fields as described in the doc ([here](https://apps.ankiweb.net/docs/manual.html#conditional-replacement)). For example I'd like to make this work : 

`{{#info-Factor:}} Factor={{info-Factor:}} {{/info-Factor:}}`

**Comment by ijgnd** [comment]
As far as I see this is no longer supported: https://github.com/ijgnd/anki21__reviewer_additional_card_fields/issues/3#issuecomment-583844966

If you have an idea or fix I'd be happy to merge it.

**Comment by thiswillbeyourgithub** [comment]
I am not good enough to provide you with any help, sorry ! Thanks anyway for the addon

**Comment by ijgnd** [comment]
I just saw a different solution using javascript at https://anki.tenderapp.com/discussions/add-ons/40804-additional-card-fields-official-thread#comment_48181511
