### ISSUE TITLE
Anki 2.1.24beta2 error

### ISSUE THREAD

**Issue by AnKingMed** [ijgnd/anki21__reviewer_additional_card_fields#7]
Looks like the new beta introduced something incompatible with this: 

> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
> Debug info:
> Anki 2.1.24 (9dda5cf6) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
> Platform: Mac 10.15.4
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2020-03-28 10:54:05
> Add-ons possibly involved: ⁨Additional Card Fields Fork for 21, Web Browser - Search terms Import texts and images automatically⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt/webview.py", line 31, in cmd
>   File "aqt/webview.py", line 97, in _onCmd
>   File "aqt/webview.py", line 500, in _onBridgeCmd
>   File "aqt/overview.py", line 67, in _linkHandler
>   File "aqt/main.py", line 596, in moveToState
>   File "aqt/main.py", line 627, in _reviewState
>   File "aqt/reviewer.py", line 55, in show
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/864545277/review_controller.py", line 101, in wrapped
>     originalResult = originalFunction(self)
>   File "aqt/reviewer.py", line 108, in nextCard
>   File "aqt/reviewer.py", line 188, in _showQuestion
>   File "anki/cards.py", line 128, in question
>   File "anki/cards.py", line 147, in render_output
>   File "anki/template.py", line 121, in render_card
>   File "anki/template.py", line 178, in render_card_from_context
>   File "anki/template.py", line 210, in apply_custom_filters
>   File "anki/hooks.py", line 273, in __call__
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/744725736/new_additional_card_fields.py", line 129, in on_field_filter
>     context.extra_state["info_fields"] = get_all_fields(context)
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/744725736/new_additional_card_fields.py", line 152, in get_all_fields
>     (first, last, cnt, total) = mw.col.db.first(
> TypeError: first() got an unexpected keyword argument 'id'
>

**Comment by ijgnd** [comment]
Thanks for notifying me. 

I just added c51edbb

I uploaded an updated version to https://ankiweb.net/shared/info/744725736 . Could you test and let me know if you run into another problem.

**Comment by AnKingMed** [comment]
Works great for me so far. I tested it on 2.1.23 and 2.1.24beta2.
