### ISSUE TITLE
Ease field doesn't work on mobile. Possible to use card styling to hide certain fields on mobile?

### ISSUE THREAD

**Issue by bradydjohnson** [ijgnd/anki21__reviewer_additional_card_fields#9]
I'd like to use {{info-Ease:}} to display the ease on my cards, however it seems to be incompatible with Anki iOS mobile. Is it possible to use card styling to hide certain fields on mobile?

**Comment by ijgnd** [comment]
If you have some text that only makes sense with the additional card fields you can hide it on mobile like [this](https://github.com/ijgnd/anki21__reviewer_additional_card_fields/issues/3#issuecomment-590822074). 

Does this solve your problem?

**Comment by bradydjohnson** [comment]
I think so! Thank you!
